name: Collect Instagram Data

on:
  schedule:
    - cron: '0 0 * * *'  # Täglich um Mitternacht ausführen
  push:
    branches:
      - main

jobs:
  collect-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas plotly dash python-dotenv

    - name: Run data collection script
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        USER_ID: ${{ secrets.USER_ID }}
        API_URL: ${{ secrets.API_URL }}
      run: |
        python collect_data.py

    - name: Commit and push results
      run: |
        git add data/*.csv
        git commit -m 'Update Instagram data and generate dashboard' || echo "No changes to commit"
        git push || echo "No changes to push"